### ISSUE TITLE
Initial Features Feedback

### ISSUE THREAD

**Issue by edherm** [icey-franken/projectKIL#1]
Before I give you any feedback, I need to see your feature list! I don't know where to find your _As a_, _I want_, _so that_ statements in your repo, so I can't review them.

Check out Curtis's video at the 6:25 mark for a description of the features. Be sure to include one for user auth (login, logout, signup) in addition to your other MVPs.

Y'all have done a TON of work on those other markdowns, and I can't wait to dig into them, but I need to review your feature list first!

**Comment by icey-franken** [comment]
Whoops! It was named features.md. I changed it to feature-list.md, located
in the documentation directory.

**Comment by icey-franken** [comment]
I’ll also add that we haven’t done all the feature descriptions for user
authorization - just one description for a general user. We can get that
done today.

**Comment by edherm** [comment]
Now that I've found the correct `.md` file...

Your features look good! Mainly, I want you to focus on broadening your feature-list definitions. There's only the one thing to check off. Let me know any questions that you might have after you have discussed this with your group!

### FEATURE-LIST
**Projects**
- [ ] Think about other CRUD functionalities that might be involved in projects. Right now, I'm seeing a description of viewing an index, but nothing about creation, or viewing individual projects.


I have started writing down an issue for your feature-lists, but I will post that separately (and once you tell me you are finished writing them).

**Comment by icey-franken** [comment]
Hi Ed - I think we took care of it. Let us know.

P.S. how cool that email threads (or at least my replies via email) show up here!
